
DatasetAttribution:
  - "Max-Planck Institute for Biogeochemistry. Joint Research Centre"

DatasetGroups:
   - Identifier: S4T
     Title: Space for Time results for Africa and Europe (2018)
     Description: This is a zarr dataset group description!

Datasets:
  - Identifier: local
    Title: Space for Time results for Africa and Europe (2018)
    GroupId: first_local
    #BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: file
    Path: /data/data.zarr
    Style: default
    TimeSeriesDataset: local_ts
    Variables:
      - "LST_delta_TREES to GRASS"
    PlaceGroups:
      - PlaceGroupRef: inside-cube


PlaceGroups:
  - Identifier: inside-cube
    Title: Countries
    Path: places/initial_places.geojson
#Styles:
#  - Identifier: default
  